# Generated by Django 4.2.19 on 2025-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationmetric",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
