# Generated by Django 4.2.19 on 2025-04-13 11:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_enable_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteinsequence",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="jobqueue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobqueue",
            name="job_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobqueue",
            name="priority",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="jobqueue",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="log",
            name="action",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="log",
            name="component",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="log",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="mlranking",
            name="binding_efficiency_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="mlranking",
            name="overall_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="mlranking",
            name="ranking_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="mlranking",
            name="solubility_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="mlranking",
            name="stability_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="confidence_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="plddt_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="prediction_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="prediction",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="proteinsequence",
            name="organism",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="proteinsequence",
            name="sequence_length",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="proteinsequence",
            name="sequence_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="proteinsequence",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="proteinsequence",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="active_jobs",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="cpu_usage",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="disk_usage",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="memory_usage",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemmetric",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="und-x-icu", db_index=True, max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="energy",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="rg",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="rmsd",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="stability_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="status",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="validationmetric",
            name="validation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="jobqueue",
            index=models.Index(
                fields=["created_at", "status"], name="job_queue_created_588864_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobqueue",
            index=models.Index(
                fields=["job_type", "priority"], name="job_queue_job_typ_bb72d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["timestamp", "action"], name="logs_timesta_cc4662_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["status", "component"], name="logs_status_1a1a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlranking",
            index=models.Index(
                fields=["ranking_date"], name="ml_ranking_ranking_077dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlranking",
            index=models.Index(
                fields=[
                    "stability_score",
                    "solubility_score",
                    "binding_efficiency_score",
                ],
                name="ml_ranking_stabili_41647c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["prediction_date", "status"],
                name="predictions_predict_9f01ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["plddt_score", "confidence_score"],
                name="predictions_plddt_s_38c04f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proteinsequence",
            index=models.Index(
                fields=["sequence_name", "upload_date"],
                name="protein_seq_sequenc_cd4769_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proteinsequence",
            index=models.Index(
                fields=["organism", "sequence_length"],
                name="protein_seq_organis_d166d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proteinsequence",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="protein_seq_search__6f889f_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["role_name"], name="role_role_na_a36144_idx"),
        ),
        migrations.AddIndex(
            model_name="systemmetric",
            index=models.Index(
                fields=["timestamp"], name="system_metr_timesta_206ca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemmetric",
            index=models.Index(
                fields=["cpu_usage", "memory_usage", "disk_usage"],
                name="system_metr_cpu_usa_bda46b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "created_at"], name="users_email_707aef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationmetric",
            index=models.Index(
                fields=["validation_date", "status"],
                name="validation__validat_039041_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationmetric",
            index=models.Index(
                fields=["rmsd", "rg", "energy"], name="validation__rmsd_5de186_idx"
            ),
        ),
    ]
