# Generated by Django 4.2.17 on 2025-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationmetric",
            name="structure_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
