use crate::error::EngineError;
use crate::runner::{ComputeRunner, RunResult};
use proteus_core::models::{PipelineJob, PipelineTier, Sequence};
use std::path::{Path, PathBuf};
use tracing::info;

pub struct SimulatedRunner;

impl SimulatedRunner {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SimulatedRunner {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl ComputeRunner for SimulatedRunner {
    async fn execute_job(
        &self,
        job: &PipelineJob,
        sequence: &Sequence,
        work_dir: &Path,
    ) -> Result<RunResult, EngineError> {
        if proteus_core::complex::ComplexSpec::is_spec(&sequence.fasta) {
            return Err(EngineError::Pipeline(
                "complexes, ligands, MSA options and several samples need the sota tier with \
                 --runner oci; LABEL"
                    .replace("LABEL", "the simulator draws one helix"),
            ));
        }
        info!(
            "SimulatedRunner executing job {} (Tier: {:?}) for sequence '{}'",
            job.id, job.tier, sequence.header
        );

        tokio::fs::create_dir_all(work_dir).await?;
        let pdb_filename = format!("{}_predicted.pdb", job.id);
        let pdb_path: PathBuf = work_dir.join(&pdb_filename);

        // Generate synthetic alpha-helix backbone with valid CA coordinates
        // pitch: 1.5A per residue, 3.6 residues per turn (100 deg = 1.745 rad)
        let mut pdb_lines = Vec::new();
        pdb_lines.push(format!(
            "HEADER    SYNTHETIC STRUCTURE FOR {}",
            sequence.header
        ));
        pdb_lines.push("TITLE     GENERATED BY PROTEUS SIMULATED ENGINE".to_string());

        let base_plddt = match job.tier {
            PipelineTier::FastScreening => 82.5,
            PipelineTier::HighFidelity => 91.2,
            PipelineTier::FullValidation => 94.0,
        };

        let radius = 2.3; // alpha helix CA radius
        for (i, aa) in sequence.fasta.chars().enumerate() {
            let angle = (i as f64) * 1.74533;
            let x = radius * angle.cos();
            let y = radius * angle.sin();
            let z = (i as f64) * 1.5;

            // Introduce slight variation in plddt
            let plddt = (base_plddt + ((i % 5) as f64 * 1.2) - 2.0).clamp(50.0, 99.0);

            // PDB ATOM record format
            let record = format!(
                "ATOM  {:5} {:^4} {:3} A{:4}    {:8.3}{:8.3}{:8.3}{:6.2}{:6.2}          {:>2}",
                i + 1,
                "CA",
                aa_to_three_letter(aa),
                i + 1,
                x,
                y,
                z,
                1.00,
                plddt,
                "C"
            );
            pdb_lines.push(record);
        }
        pdb_lines.push("END".to_string());

        tokio::fs::write(&pdb_path, pdb_lines.join("\n")).await?;

        let metadata = serde_json::json!({
            "engine": crate::runner::ENGINE_SIMULATED,
            "runner": "simulated",
            "tier": format!("{:?}", job.tier),
            "residue_count": sequence.length,
            "estimated_time_ms": 150
        });

        Ok(RunResult {
            pdb_path,
            plddt: Some(base_plddt),
            metadata: Some(metadata),
        })
    }
}

fn aa_to_three_letter(c: char) -> &'static str {
    match c {
        'A' => "ALA",
        'C' => "CYS",
        'D' => "ASP",
        'E' => "GLU",
        'F' => "PHE",
        'G' => "GLY",
        'H' => "HIS",
        'I' => "ILE",
        'K' => "LYS",
        'L' => "LEU",
        'M' => "MET",
        'N' => "ASN",
        'P' => "PRO",
        'Q' => "GLN",
        'R' => "ARG",
        'S' => "SER",
        'T' => "THR",
        'V' => "VAL",
        'W' => "TRP",
        'Y' => "TYR",
        _ => "UNK",
    }
}
