[package]
name = "proteus-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Asynchronous DAG pipeline scheduler and OCI/Podman container runner for Proteus."

[dependencies]
proteus-core = { workspace = true }
proteus-storage = { workspace = true }
bollard = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
glob = { workspace = true }
futures-util = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
