// @generated by scripts/convert_geostd.py from Phenix geostd; do not edit by hand.
// Source: https://github.com/phenix-project/geostd (BSD-3-style LBNL licence);
// see crates/proteus-core/data/cdl/NOTICE for provenance and licence text.

use super::library_types::*;

/// Heavy-atom restraints of the 20 standard amino acids and selenomethionine (geostd).
pub(super) static RESIDUES: &[ResidueDef] = &[
    ResidueDef {
        name: "ALA",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.5, esd: 1.5 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.4, esd: 1.5 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.4849960753673224, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "ARG",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "CD", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CD", b: "NE", ideal: 1.458, esd: 0.014 },
            BondDef { a: "NE", b: "CZ", ideal: 1.326, esd: 0.011 },
            BondDef { a: "CZ", b: "NH1", ideal: 1.323, esd: 0.014 },
            BondDef { a: "CZ", b: "NH2", ideal: 1.33, esd: 0.013 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "CD", ideal: 111.3, esd: 2.3 },
            AngleDef { a: "CG", b: "CD", c: "NE", ideal: 112.0, esd: 2.2 },
            AngleDef { a: "CD", b: "NE", c: "CZ", ideal: 124.4, esd: 1.4 },
            AngleDef { a: "NH1", b: "CZ", c: "NH2", ideal: 119.3, esd: 1.3 },
            AngleDef { a: "NE", b: "CZ", c: "NH1", ideal: 121.5, esd: 1.0 },
            AngleDef { a: "NE", b: "CZ", c: "NH2", ideal: 119.2, esd: 0.9 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CD", 0.095), ("NE", 0.02), ("CZ", 0.02), ("NH1", 0.02), ("NH2", 0.02)],
        ],
    },
    ResidueDef {
        name: "ASN",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.516, esd: 0.025 },
            BondDef { a: "CG", b: "OD1", ideal: 1.231, esd: 0.019 },
            BondDef { a: "CG", b: "ND2", ideal: 1.328, esd: 0.021 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 112.6, esd: 1.0 },
            AngleDef { a: "OD1", b: "CG", c: "ND2", ideal: 122.6, esd: 1.0 },
            AngleDef { a: "CB", b: "CG", c: "OD1", ideal: 120.8, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "ND2", ideal: 116.4, esd: 1.5 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CG", 0.02), ("CB", 0.02), ("OD1", 0.02), ("ND2", 0.02)],
        ],
    },
    ResidueDef {
        name: "ASP",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.516, esd: 0.025 },
            BondDef { a: "CG", b: "OD1", ideal: 1.249, esd: 0.019 },
            BondDef { a: "CG", b: "OD2", ideal: 1.249, esd: 0.019 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 112.6, esd: 1.0 },
            AngleDef { a: "OD1", b: "CG", c: "OD2", ideal: 122.9, esd: 2.4 },
            AngleDef { a: "CB", b: "CG", c: "OD1", ideal: 118.4, esd: 2.3 },
            AngleDef { a: "CB", b: "CG", c: "OD2", ideal: 118.4, esd: 2.3 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CG", 0.02), ("CB", 0.02), ("OD1", 0.02), ("OD2", 0.02)],
        ],
    },
    ResidueDef {
        name: "CYS",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "SG", ideal: 1.808, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "SG", ideal: 114.4, esd: 2.3 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "GLN",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "CD", ideal: 1.516, esd: 0.025 },
            BondDef { a: "CD", b: "OE1", ideal: 1.231, esd: 0.019 },
            BondDef { a: "CD", b: "NE2", ideal: 1.328, esd: 0.021 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "CD", ideal: 112.6, esd: 1.7 },
            AngleDef { a: "OE1", b: "CD", c: "NE2", ideal: 122.6, esd: 1.0 },
            AngleDef { a: "CG", b: "CD", c: "OE1", ideal: 120.8, esd: 2.0 },
            AngleDef { a: "CG", b: "CD", c: "NE2", ideal: 116.4, esd: 1.5 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CD", 0.02), ("CG", 0.02), ("OE1", 0.02), ("NE2", 0.02)],
        ],
    },
    ResidueDef {
        name: "GLU",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "CD", ideal: 1.516, esd: 0.025 },
            BondDef { a: "CD", b: "OE1", ideal: 1.249, esd: 0.019 },
            BondDef { a: "CD", b: "OE2", ideal: 1.249, esd: 0.019 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "CD", ideal: 112.6, esd: 1.7 },
            AngleDef { a: "OE1", b: "CD", c: "OE2", ideal: 122.9, esd: 2.4 },
            AngleDef { a: "CG", b: "CD", c: "OE1", ideal: 118.4, esd: 2.3 },
            AngleDef { a: "CG", b: "CD", c: "OE2", ideal: 118.4, esd: 2.3 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CD", 0.02), ("CG", 0.02), ("OE1", 0.02), ("OE2", 0.02)],
        ],
    },
    ResidueDef {
        name: "GLY",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.451, esd: 0.016 },
            BondDef { a: "CA", b: "C", ideal: 1.516, esd: 0.018 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "N", b: "CA", c: "C", ideal: 113.3, esd: 2.9 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 2.1 },
        ],
        chiralities: &[
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "HIS",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.497, esd: 0.014 },
            BondDef { a: "CG", b: "CD2", ideal: 1.354, esd: 0.011 },
            BondDef { a: "CG", b: "ND1", ideal: 1.378, esd: 0.011 },
            BondDef { a: "ND1", b: "CE1", ideal: 1.321, esd: 0.01 },
            BondDef { a: "CE1", b: "NE2", ideal: 1.321, esd: 0.01 },
            BondDef { a: "NE2", b: "CD2", ideal: 1.374, esd: 0.011 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 113.8, esd: 1.0 },
            AngleDef { a: "CB", b: "CG", c: "CD2", ideal: 131.2, esd: 1.3 },
            AngleDef { a: "ND1", b: "CG", c: "CD2", ideal: 106.1, esd: 1.0 },
            AngleDef { a: "CB", b: "CG", c: "ND1", ideal: 122.7, esd: 1.5 },
            AngleDef { a: "CG", b: "ND1", c: "CE1", ideal: 109.3, esd: 1.7 },
            AngleDef { a: "ND1", b: "CE1", c: "NE2", ideal: 108.4, esd: 1.0 },
            AngleDef { a: "CE1", b: "NE2", c: "CD2", ideal: 109.0, esd: 1.0 },
            AngleDef { a: "CG", b: "CD2", c: "NE2", ideal: 107.2, esd: 1.0 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CB", 0.02), ("CG", 0.02), ("ND1", 0.02), ("CE1", 0.02), ("CD2", 0.02), ("NE2", 0.02)],
        ],
    },
    ResidueDef {
        name: "ILE",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.54, esd: 0.027 },
            BondDef { a: "CB", b: "CG1", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CG1", b: "CD1", ideal: 1.513, esd: 0.039 },
            BondDef { a: "CB", b: "CG2", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 111.6, esd: 2.0 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 111.5, esd: 1.7 },
            AngleDef { a: "CG1", b: "CB", c: "CG2", ideal: 110.7, esd: 3.0 },
            AngleDef { a: "CA", b: "CB", c: "CG1", ideal: 110.4, esd: 1.7 },
            AngleDef { a: "CB", b: "CG1", c: "CD1", ideal: 113.8, esd: 2.1 },
            AngleDef { a: "CA", b: "CB", c: "CG2", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.4333688117423895, both_signs: false },
            ChiralDef { atoms: ["CB", "CA", "CG1", "CG2"], ideal: 2.644744159798795, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "LEU",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CG", b: "CD1", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CG", b: "CD2", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 116.3, esd: 3.5 },
            AngleDef { a: "CD1", b: "CG", c: "CD2", ideal: 110.8, esd: 2.2 },
            AngleDef { a: "CB", b: "CG", c: "CD1", ideal: 110.7, esd: 3.0 },
            AngleDef { a: "CB", b: "CG", c: "CD2", ideal: 110.7, esd: 3.0 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
            ChiralDef { atoms: ["CG", "CB", "CD1", "CD2"], ideal: -2.5896284220730137, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "LYS",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "CD", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CD", b: "CE", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CE", b: "NZ", ideal: 1.489, esd: 0.03 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "CD", ideal: 111.3, esd: 2.3 },
            AngleDef { a: "CG", b: "CD", c: "CE", ideal: 111.3, esd: 2.3 },
            AngleDef { a: "CD", b: "CE", c: "NZ", ideal: 111.9, esd: 3.2 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "MET",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "SD", ideal: 1.803, esd: 0.025 },
            BondDef { a: "SD", b: "CE", ideal: 1.791, esd: 0.025 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "SD", ideal: 112.7, esd: 3.0 },
            AngleDef { a: "CG", b: "SD", c: "CE", ideal: 100.9, esd: 2.2 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "PHE",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.502, esd: 0.023 },
            BondDef { a: "CG", b: "CD2", ideal: 1.384, esd: 0.021 },
            BondDef { a: "CG", b: "CD1", ideal: 1.384, esd: 0.021 },
            BondDef { a: "CD1", b: "CE1", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CE1", b: "CZ", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CZ", b: "CE2", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CE2", b: "CD2", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 113.8, esd: 1.0 },
            AngleDef { a: "CB", b: "CG", c: "CD2", ideal: 120.7, esd: 1.7 },
            AngleDef { a: "CD1", b: "CG", c: "CD2", ideal: 118.6, esd: 1.5 },
            AngleDef { a: "CB", b: "CG", c: "CD1", ideal: 120.7, esd: 1.7 },
            AngleDef { a: "CG", b: "CD1", c: "CE1", ideal: 120.7, esd: 1.7 },
            AngleDef { a: "CG", b: "CD2", c: "CE2", ideal: 120.7, esd: 1.7 },
            AngleDef { a: "CD1", b: "CE1", c: "CZ", ideal: 120.0, esd: 1.8 },
            AngleDef { a: "CE1", b: "CZ", c: "CE2", ideal: 120.0, esd: 1.8 },
            AngleDef { a: "CZ", b: "CE2", c: "CD2", ideal: 120.0, esd: 1.8 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CB", 0.02), ("CG", 0.02), ("CD1", 0.02), ("CE1", 0.02), ("CZ", 0.02), ("CE2", 0.02), ("CD2", 0.02)],
        ],
    },
    ResidueDef {
        name: "PRO",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.466, esd: 0.015 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.492, esd: 0.05 },
            BondDef { a: "CG", b: "CD", ideal: 1.503, esd: 0.034 },
            BondDef { a: "CD", b: "N", ideal: 1.473, esd: 0.014 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CA", b: "N", c: "CD", ideal: 112.0, esd: 1.4 },
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 103.0, esd: 1.1 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 104.5, esd: 1.9 },
            AngleDef { a: "CB", b: "CG", c: "CD", ideal: 106.1, esd: 3.2 },
            AngleDef { a: "N", b: "CD", c: "CG", ideal: 103.2, esd: 1.5 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 112.1, esd: 2.5 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 119.0, esd: 3.0 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.7183777454750855, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "SER",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "OG", ideal: 1.417, esd: 0.02 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "OG", ideal: 111.1, esd: 2.0 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "THR",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.54, esd: 0.027 },
            BondDef { a: "CB", b: "OG1", ideal: 1.433, esd: 0.016 },
            BondDef { a: "CB", b: "CG2", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 109.1, esd: 2.2 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 111.5, esd: 1.7 },
            AngleDef { a: "OG1", b: "CB", c: "CG2", ideal: 109.3, esd: 2.0 },
            AngleDef { a: "CA", b: "CB", c: "OG1", ideal: 109.6, esd: 1.5 },
            AngleDef { a: "CA", b: "CB", c: "CG2", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.52601764314869, both_signs: false },
            ChiralDef { atoms: ["CB", "CA", "OG1", "CG2"], ideal: 2.5517268889048568, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "TRP",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.498, esd: 0.031 },
            BondDef { a: "CG", b: "CD2", ideal: 1.433, esd: 0.018 },
            BondDef { a: "CG", b: "CD1", ideal: 1.365, esd: 0.025 },
            BondDef { a: "CD1", b: "NE1", ideal: 1.374, esd: 0.021 },
            BondDef { a: "NE1", b: "CE2", ideal: 1.37, esd: 0.011 },
            BondDef { a: "CE2", b: "CZ2", ideal: 1.394, esd: 0.021 },
            BondDef { a: "CE2", b: "CD2", ideal: 1.409, esd: 0.017 },
            BondDef { a: "CD2", b: "CE3", ideal: 1.398, esd: 0.016 },
            BondDef { a: "CE3", b: "CZ3", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CZ3", b: "CH2", ideal: 1.4, esd: 0.025 },
            BondDef { a: "CH2", b: "CZ2", ideal: 1.368, esd: 0.019 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 113.6, esd: 1.9 },
            AngleDef { a: "CB", b: "CG", c: "CD2", ideal: 126.8, esd: 1.4 },
            AngleDef { a: "CD1", b: "CG", c: "CD2", ideal: 106.3, esd: 1.6 },
            AngleDef { a: "CB", b: "CG", c: "CD1", ideal: 126.9, esd: 1.5 },
            AngleDef { a: "CG", b: "CD1", c: "NE1", ideal: 110.2, esd: 1.3 },
            AngleDef { a: "CD1", b: "NE1", c: "CE2", ideal: 108.9, esd: 1.8 },
            AngleDef { a: "NE1", b: "CE2", c: "CZ2", ideal: 130.1, esd: 1.5 },
            AngleDef { a: "CD2", b: "CE2", c: "CZ2", ideal: 122.4, esd: 1.0 },
            AngleDef { a: "NE1", b: "CE2", c: "CD2", ideal: 107.4, esd: 1.3 },
            AngleDef { a: "CE2", b: "CD2", c: "CE3", ideal: 118.8, esd: 1.0 },
            AngleDef { a: "CE2", b: "CD2", c: "CG", ideal: 107.2, esd: 1.2 },
            AngleDef { a: "CG", b: "CD2", c: "CE3", ideal: 133.9, esd: 1.0 },
            AngleDef { a: "CD2", b: "CE3", c: "CZ3", ideal: 118.6, esd: 1.3 },
            AngleDef { a: "CE3", b: "CZ3", c: "CH2", ideal: 121.1, esd: 1.3 },
            AngleDef { a: "CZ3", b: "CH2", c: "CZ2", ideal: 121.5, esd: 1.3 },
            AngleDef { a: "CH2", b: "CZ2", c: "CE2", ideal: 117.5, esd: 1.3 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CB", 0.02), ("CG", 0.02), ("CD1", 0.02), ("NE1", 0.02), ("CD2", 0.02), ("CE2", 0.02), ("CZ2", 0.02), ("CH2", 0.02), ("CE3", 0.02), ("CZ3", 0.02)],
        ],
    },
    ResidueDef {
        name: "TYR",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.512, esd: 0.022 },
            BondDef { a: "CG", b: "CD2", ideal: 1.389, esd: 0.021 },
            BondDef { a: "CG", b: "CD1", ideal: 1.389, esd: 0.021 },
            BondDef { a: "CD1", b: "CE1", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CE1", b: "CZ", ideal: 1.378, esd: 0.024 },
            BondDef { a: "CZ", b: "OH", ideal: 1.376, esd: 0.021 },
            BondDef { a: "CZ", b: "CE2", ideal: 1.378, esd: 0.024 },
            BondDef { a: "CE2", b: "CD2", ideal: 1.382, esd: 0.03 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 113.9, esd: 1.8 },
            AngleDef { a: "CB", b: "CG", c: "CD2", ideal: 120.8, esd: 1.5 },
            AngleDef { a: "CD1", b: "CG", c: "CD2", ideal: 118.1, esd: 1.5 },
            AngleDef { a: "CB", b: "CG", c: "CD1", ideal: 120.8, esd: 1.5 },
            AngleDef { a: "CG", b: "CD1", c: "CE1", ideal: 121.2, esd: 1.5 },
            AngleDef { a: "CG", b: "CD2", c: "CE2", ideal: 121.2, esd: 1.5 },
            AngleDef { a: "CD1", b: "CE1", c: "CZ", ideal: 119.6, esd: 1.8 },
            AngleDef { a: "OH", b: "CZ", c: "CE2", ideal: 119.9, esd: 3.0 },
            AngleDef { a: "CE1", b: "CZ", c: "OH", ideal: 119.9, esd: 3.0 },
            AngleDef { a: "CE1", b: "CZ", c: "CE2", ideal: 120.3, esd: 2.0 },
            AngleDef { a: "CZ", b: "CE2", c: "CD2", ideal: 119.6, esd: 1.8 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.5104031004792793, both_signs: false },
        ],
        planes: &[
            &[("CB", 0.02), ("CG", 0.02), ("CD1", 0.02), ("CE1", 0.02), ("CZ", 0.02), ("CE2", 0.02), ("CD2", 0.02), ("OH", 0.02)],
        ],
    },
    ResidueDef {
        name: "VAL",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.54, esd: 0.027 },
            BondDef { a: "CB", b: "CG1", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CB", b: "CG2", ideal: 1.521, esd: 0.033 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 111.4, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 111.5, esd: 1.7 },
            AngleDef { a: "CG1", b: "CB", c: "CG2", ideal: 110.8, esd: 2.2 },
            AngleDef { a: "CA", b: "CB", c: "CG1", ideal: 110.4, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG2", ideal: 110.4, esd: 1.7 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.0, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.4411468865489776, both_signs: false },
            ChiralDef { atoms: ["CB", "CA", "CG1", "CG2"], ideal: -2.629169024624658, both_signs: false },
        ],
        planes: &[
        ],
    },
    ResidueDef {
        name: "MSE",
        bonds: &[
            BondDef { a: "N", b: "CA", ideal: 1.458, esd: 0.019 },
            BondDef { a: "CA", b: "CB", ideal: 1.53, esd: 0.02 },
            BondDef { a: "CB", b: "CG", ideal: 1.52, esd: 0.03 },
            BondDef { a: "CG", b: "SE", ideal: 1.95, esd: 0.03 },
            BondDef { a: "SE", b: "CE", ideal: 1.95, esd: 0.03 },
            BondDef { a: "CA", b: "C", ideal: 1.525, esd: 0.021 },
            BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 },
        ],
        angles: &[
            AngleDef { a: "CB", b: "CA", c: "C", ideal: 110.1, esd: 1.9 },
            AngleDef { a: "N", b: "CA", c: "CB", ideal: 110.5, esd: 1.7 },
            AngleDef { a: "CA", b: "CB", c: "CG", ideal: 114.1, esd: 2.0 },
            AngleDef { a: "CB", b: "CG", c: "SE", ideal: 112.7, esd: 3.0 },
            AngleDef { a: "CG", b: "SE", c: "CE", ideal: 98.923, esd: 2.2 },
            AngleDef { a: "N", b: "CA", c: "C", ideal: 111.2, esd: 2.8 },
            AngleDef { a: "CA", b: "C", c: "O", ideal: 120.8, esd: 1.7 },
        ],
        chiralities: &[
            ChiralDef { atoms: ["CA", "N", "CB", "C"], ideal: -2.503181344935401, both_signs: false },
        ],
        planes: &[
        ],
    },
];

/// Peptide links: TRANS, and PTRANS to a proline; heavy atoms only.
pub(super) static LINKS: &[LinkDef] = &[
    LinkDef {
        id: "TRANS",
        bonds: &[
            LinkBondDef { a: (1, "C"), b: (2, "N"), ideal: 1.329, esd: 0.014 },
        ],
        angles: &[
            LinkAngleDef { atoms: [(1, "O"), (1, "C"), (2, "N")], ideal: 123.0, esd: 1.6 },
            LinkAngleDef { atoms: [(1, "CA"), (1, "C"), (2, "N")], ideal: 116.2, esd: 2.0 },
            LinkAngleDef { atoms: [(1, "C"), (2, "N"), (2, "CA")], ideal: 121.7, esd: 1.8 },
        ],
        planes: &[
            &[(1, "CA", 0.02), (1, "C", 0.02), (1, "O", 0.02), (2, "N", 0.02)],
        ],
    },
    LinkDef {
        id: "PTRANS",
        bonds: &[
            LinkBondDef { a: (1, "C"), b: (2, "N"), ideal: 1.341, esd: 0.016 },
        ],
        angles: &[
            LinkAngleDef { atoms: [(1, "O"), (1, "C"), (2, "N")], ideal: 123.0, esd: 1.6 },
            LinkAngleDef { atoms: [(1, "CA"), (1, "C"), (2, "N")], ideal: 116.9, esd: 1.5 },
            LinkAngleDef { atoms: [(1, "C"), (2, "N"), (2, "CD")], ideal: 125.0, esd: 4.1 },
            LinkAngleDef { atoms: [(1, "C"), (2, "N"), (2, "CA")], ideal: 122.6, esd: 5.0 },
        ],
        planes: &[
            &[(1, "CA", 0.02), (1, "C", 0.02), (1, "O", 0.02), (2, "N", 0.02)],
            &[(1, "C", 0.05), (2, "N", 0.05), (2, "CA", 0.05), (2, "CD", 0.05)],
        ],
    },
];

/// The C-terminal carboxylate modification, applied when the residue carries OXT.
pub(super) static COO: ModDef = ModDef {
    bonds: &[
        ModBondDef { add: false, bond: BondDef { a: "C", b: "O", ideal: 1.231, esd: 0.02 } },
        ModBondDef { add: true, bond: BondDef { a: "C", b: "OXT", ideal: 1.231, esd: 0.02 } },
    ],
    angles: &[
        ModAngleDef { add: false, angle: AngleDef { a: "CA", b: "C", c: "O", ideal: 121.0, esd: 3.0 } },
        ModAngleDef { add: true, angle: AngleDef { a: "CA", b: "C", c: "OXT", ideal: 121.0, esd: 3.0 } },
        ModAngleDef { add: true, angle: AngleDef { a: "O", b: "C", c: "OXT", ideal: 118.0, esd: 3.0 } },
    ],
    planes: &[
        &[("C", 0.02), ("CA", 0.02), ("O", 0.02), ("OXT", 0.02)],
    ],
};
