#!/usr/bin/env bash
# Build the viewer gallery: one self-contained Proteus page per structure plus an index, in
# OUT (default target/gallery). Nothing is published; .github/workflows/pages.yml deploys it
# when run by hand.
#
#   scripts/gallery.sh [OUT]      # needs a built proteus (PROTEUS_BIN or target/release/proteus)
set -euo pipefail
cd "$(dirname "$0")/.."
OUT="${1:-target/gallery}"
BIN="${PROTEUS_BIN:-target/release/proteus}"
mkdir -p "$OUT"
python3 validate/fetch.py >/dev/null

# id | file | title | one line on what it shows
ENTRIES=(
  "1pgb|validate/corpus/1pgb.pdb|Protein G, B1 domain|A 56-residue crystal structure: one helix packed on a four-stranded sheet."
  "af-p04637|validate/corpus/af-p04637.cif|p53, AlphaFold model|393 residues coloured by pLDDT: a confident DNA-binding core, disordered termini."
  "4hhb|validate/corpus/4hhb.pdb|Haemoglobin (deoxy)|Four chains, 574 residues, almost all helix."
  "1crn|validate/corpus/1crn.pdb|Crambin|46 residues held by three disulfide bonds."
  "6vxx|validate/corpus/6vxx.cif|SARS-CoV-2 spike, closed|A cryo-EM trimer, 2,916 modelled residues."
  "1aon|validate/corpus/1aon.pdb|GroEL–GroES|A chaperonin of 8,015 residues: the scale test."
)

cards=""
for e in "${ENTRIES[@]}"; do
  IFS='|' read -r id file title line <<<"$e"
  RUST_LOG=off "$BIN" view "$file" --html "$OUT/$id.html" >/dev/null
  size=$(( $(stat -c%s "$OUT/$id.html") / 1024 ))
  cards+="<a class=\"card\" href=\"$id.html\"><span class=\"id\">$id</span><b>$title</b><span class=\"line\">$line</span><span class=\"size\">$size KB · opens offline</span></a>"
done

# The index: brand colours (proteus_render::brand::DARK) and the lockup from docs/brand.
lockup=$(sed 's/ xmlns="http:\/\/www.w3.org\/2000\/svg"//' docs/brand/proteus-lockup-dark.svg)
cat >"$OUT/index.html" <<HTML
<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Proteus viewer gallery</title>
<meta name="description" content="Protein structures drawn by Proteus in the browser: the terminal's own ribbon, in WebGL2, with its measurements.">
<style>
:root{--ground:#141c10;--surface:#1b2516;--line:#5a6042;--text:#fbffe1;--muted:#d1cf8b;--dim:#9a9f80;--accent:#99920b}
*{box-sizing:border-box}body{margin:0;background:var(--ground);color:var(--text);font:15px/1.55 ui-sans-serif,system-ui,sans-serif}
main{max-width:1040px;margin:0 auto;padding:48px 20px 64px}
.lockup svg{width:min(460px,100%);height:auto;display:block}
p.lede{color:var(--muted);max-width:62ch;margin:18px 0 36px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}
.card{display:flex;flex-direction:column;gap:6px;padding:18px;border:1px solid var(--line);background:var(--surface);color:var(--text);text-decoration:none}
.card:hover,.card:focus-visible{border-color:var(--accent);outline:none}
.id{font:12px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase;color:var(--accent)}
.line{color:var(--muted)}.size{margin-top:auto;font:12px/1 ui-monospace,monospace;color:var(--dim)}
footer{margin-top:48px;border-top:1px solid var(--line);padding-top:16px;font:12px/1.6 ui-monospace,monospace;color:var(--dim)}
code{color:var(--text);white-space:nowrap}
</style></head><body><main>
<div class="lockup">$lockup</div>
<p class="lede">Each page is one self-contained HTML file written by <code>proteus view --html</code>: the same ribbon, DSSP and measurements as the terminal viewer, drawn with WebGL2, and nothing fetched from the network. Drag to rotate, hover a residue, press <code>c</code> to change colours.</p>
<div class="grid">$cards</div>
<footer>Structures from the RCSB PDB and the AlphaFold Protein Structure Database. Generated by <code>scripts/gallery.sh</code>. <span>a s1re.sh project</span></footer>
</main></body></html>
HTML
echo "gallery: $OUT ($(ls "$OUT" | wc -l) files)"
